name: widgets_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  animate_do: ^3.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  go_router: ^7.0.0
  riverpod_annotation: ^2.1.1

dev_dependencies:
  animated_toggle_switch: ^0.6.2
  build_runner: ^2.3.3
  custom_lint: ^0.4.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2

flutter:
  uses-material-design: true

  # creamos la ruta de las assets donde estan las imagenes,fijarse en la tabulacion de assets
  assets:
    - assets/images/
